---
- name: Install packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - python-pastescript
    - git-core
    - libpq-dev
    - python-pip
    - python-virtualenv
  tags: ckan

- name: Download
  get_url: url=http://packaging.ckan.org.s3-eu-west-1.amazonaws.com/python-ckan_2.4-trusty_amd64.deb dest=/root/python-ckan.deb mode=0440
  tags: ckan

- name: Install
  apt: deb="/root/python-ckan.deb"
  notify:
    - reload apache
    - reload nginx
  tags: ckan

- name: Install python modules
  command: "pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt"
  tags: ckan

- name: Production ini
  template:
    src=production.ini.j2
    dest=/etc/ckan/default/production.ini
  tags: ckan

- name: Solr conf
  file: path=/etc/solr/conf/schema.xml state=absent
  tags: ckan

- name: Solr conf
  file: src=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml dest=/etc/solr/conf/schema.xml state=link
  tags: ckan

- name: Ckan db
  command: ckan db init
  tags: ckan

- name: Create data dir
  file: path=/etc/some_directory state=directory mode=0775 owner=www-data group=www-data
  tags: ckan
