---
- name: Install apache
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - apache2
    - libapache2-mod-wsgi
  tags: apache

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default
    state=absent
  notify:
    - reload apache
  tags: apache

- name: Enable modules
  apache2_module: state=present name={{ item }}
  with_items:
    - expires
    - rewrite
    - ssl
    - wsgi
  notify:
    - reload apache
  tags: apache
