---
- hosts: all
  sudo: true
  vars:
    debian: "wheezy"
    document_root: /vagrant/htdocs
    php_version: "5.6"
    apache_version: "2.4"

  pre_tasks:
    # Tasks that shold be runned before roles.

  post_tasks:
    # Tasks that shold be runned after roles.

  roles:
    # Installation tasks that all should used.
    - common

    # HTTP stack instllation (apache, mysql, nginx etc.).
    - apache
    - nginx

    - solr
    - postgres
    - ckan

    # Optional extras.
    - nodejs
    - gulp
