---
- name: dotdeb | add main repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org {{ debian }} all
    - deb-src http://packages.dotdeb.org {{ debian }} all
  tags: dotdeb

- name: dotdeb | add php 5.5 repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy-php55 all
    - deb-src http://packages.dotdeb.org wheezy-php55 all
  when: php_version is defined and php_version == "5.5" and debian == "wheezy"
  tags: dotdeb

- name: dotdeb | add php 5.6 repository
  apt_repository: repo='{{ item }}' update_cache=yes
  with_items:
    - deb http://packages.dotdeb.org wheezy-php56 all
    - deb-src http://packages.dotdeb.org wheezy-php56 all
  when: php_version is defined and php_version == "5.6" and debian == "wheezy"
  tags: dotdeb

- name: dotdeb | install key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg
  tags: dotdeb

- name: apt update after dotdeb
  action: apt update_cache=yes
  tags: dotdeb
