---
- name: Install postgres packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - postgresql-9.1
    - python-psycopg2
    - libpq5
  tags: postgres

- name: Create user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=ckan_default password=vagrant
  tags: postgres

- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=ckan_default encoding='UTF-8' owner=ckan_default
  tags: postgres


